### ISSUE TITLE
Daytime Player 2 starts offscreen.

### ISSUE THREAD

**Issue by ZaynabKhan** [JimmyC7834/U.stick-battle-arena#70] opened 2023-02-28 19:59 UTC
This could be a simple positioning bug, but I cannot see Player 2 when I start daytime mode. I use the left arrow key to bring it on screen. This issue is not there in nighttime.

**Comment by JimmyC7834** [comment] 2023-02-28 21:16
This is caused by the animator not being updated with an empty default visual.
Thanks for the issue.

**Comment by JimmyC7834** [comment] 2023-03-03 07:21
Fixed in new visual update #66

**Closed by JimmyC7834** 2023-03-03 07:21 UTC
